.TH "isAnyKeyPressed.h" 3 "So, 7 sty 2023" "Atak Zombie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isAnyKeyPressed.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "bool \fBisAnyKeyPressed\fP ()"
.br
.RI "Funckja sprawdza czy jakikolwiek przycisk jest wcisniety\&. "
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "bool isAnyKeyPressed ()"

.PP
Funckja sprawdza czy jakikolwiek przycisk jest wcisniety\&. 
.PP
Definicja w linii \fB13\fP pliku \fBisAnyKeyPressed\&.cpp\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Atak Zombie\&.
