.TH "strzal" 3 "So, 7 sty 2023" "Atak Zombie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strzal \- klasa sluzaca tworzeniu strzal/sztyletow  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strzelanie_player1\&.h>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBstrzal\fP (Texture *\fBstrzala\fP, float \fBszybkosc_lotu_strzaly\fP, int \fBdmg\fP)"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "Texture * \fBstrzala\fP"
.br
.ti -1c
.RI "Sprite \fBshape\fP"
.br
.ti -1c
.RI "float \fBszybkosc_lotu_strzaly\fP"
.br
.ti -1c
.RI "int \fBdmg\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
klasa sluzaca tworzeniu strzal/sztyletow 

konstruktor 
.PP
Definicja w linii \fB12\fP pliku \fBstrzelanie_player1\&.h\fP\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "strzal::strzal (Texture * strzala, float szybkosc_lotu_strzaly, int dmg)\fC [inline]\fP"

.PP
Definicja w linii \fB24\fP pliku \fBstrzelanie_player1\&.h\fP\&.
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "int strzal::dmg"
zadawane pojedyncze obrazenia z broni 
.PP
Definicja w linii \fB18\fP pliku \fBstrzelanie_player1\&.h\fP\&.
.SS "Sprite strzal::shape"
pozwala na wyswietlenie tekstury 
.PP
Definicja w linii \fB16\fP pliku \fBstrzelanie_player1\&.h\fP\&.
.SS "Texture* strzal::strzala"
zawiera wskaznik na uzywana teksture 
.PP
Definicja w linii \fB15\fP pliku \fBstrzelanie_player1\&.h\fP\&.
.SS "float strzal::szybkosc_lotu_strzaly"
predkosc broni 
.PP
Definicja w linii \fB17\fP pliku \fBstrzelanie_player1\&.h\fP\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Atak Zombie\&.
